# AUTOGENERATED! DO NOT EDIT! File to edit: _Deploy_Search_Engine_Streamlit.ipynb.

# %% auto 0
__all__ = ['IN_NOTEBOOK', 'db_path', 'db', 'cur', 'playlist', 'sel_options_dis', 'pl_sel', 'all_options', 'sel_options', 'title',
           'on_ch_checkbox']

# %% _Deploy_Search_Engine_Streamlit.ipynb 1
import streamlit as st
import sqlite3

import pandas as pd
import numpy as np

# %% _Deploy_Search_Engine_Streamlit.ipynb 3
IN_NOTEBOOK = False
db_path = ''
try: 
    print(nbdev.__version__)
except:
    IN_NOTEBOOK = True
    db_path = '/mnt/m/datamatica/posts/full-text-search-fastai-youtube-channel/'
    
st.write(st.__version__)

# %% _Deploy_Search_Engine_Streamlit.ipynb 5
db = sqlite3.connect(db_path + 'fastai_yt.db')
cur = db.cursor()

# %% _Deploy_Search_Engine_Streamlit.ipynb 6
playlist = cur.execute('SELECT playlist_id, playlist_name FROM playlist').fetchall()
playlist = {p: n for p, n in playlist}

# %% _Deploy_Search_Engine_Streamlit.ipynb 8
pl_sel = list(playlist.values())

def on_ch_checkbox():
    print('checkbox changed')
    st.session_state.default = pl_sel
    
if 'sel_all' not in st.session_state:
    st.session_state.disabled = True
    st.session_state.default = pl_sel

print('before:', st.session_state)

# %% _Deploy_Search_Engine_Streamlit.ipynb 9
st.title('Full-Text Search fastai Youtube Playlists')

all_options = st.checkbox(
    "Select all Playlists", on_change=on_ch_checkbox, 
    key='sel_all', value=True
)

sel_options = st.multiselect(
    'Select one or more Playlist(s)',
    pl_sel,
    default=st.session_state.default,
    disabled=all_options
)

if all_options:
    options = list(playlist.values())
else: 
    options = sel_options

st.write('You selected:', options)

# %% _Deploy_Search_Engine_Streamlit.ipynb 12
title = st.text_input('Search Query', 'fastcore*')
#st.write('The current movie title is', title)
